services:
  - type: web
    name: medlink
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medlink-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.2

databases:
  - name: medlink-db
    plan: free
